perfil/urls.py
from django.urls import path
from .views import Login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/index.html'), name='index'),
    path('login/', LoginView.as_view(
        template_name='perfil/index.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

prefeitura/urls.py
from django.urls import path
from .views import PrefeituraListView, PrefeituraCreate, PrefeituraEdit, PrefeituraDeleteView

app_name = 'prefeitura'

urlpatterns = [
    path('', PrefeituraListView.as_view(), name='index'),
    path('add/', PrefeituraCreate.as_view(), name='add'),
    path('edit/<pk>', PrefeituraEdit.as_view(), name='edit'),
    path('del/<pk>', PrefeituraDeleteView.as_view(), name='del'),
]

produto/urls.py
from django.urls import path
from .views import ProdutoList, ProdutoCreateView, ProdutoEdit
from .views import ProdutoDeleteView, ProdutoSearch, generate_data, Buscador
from .views import Blank

app_name = 'produto'

urlpatterns = [
    path('',  ProdutoList.as_view(), name='index'),
    path('add/', ProdutoCreateView.as_view(), name='add'),
    path('edit/<pk>', ProdutoEdit.as_view(), name='edit'),
    path('del/<pk>', ProdutoDeleteView.as_view(), name='del'),
    path('search/', ProdutoSearch.as_view(), name='search'),
    path('busca/<pk>', Buscador.as_view(), name='busca'),
    path('blank', Blank.as_view(), name='blank'),
    # path('gera/', generate_data, name='gera')
]

secretaria/urls.py
from django.urls import path
from .views import SecretariaListView, SecretariaCreateView, SecretariaEdit, SecretariaDeleteView

app_name = 'secretaria'

urlpatterns = [
    path('', SecretariaListView.as_view(), name='index'),
    path('add/', SecretariaCreateView.as_view(), name='add'),
    path('edit/<pk>', SecretariaEdit.as_view(), name='edit'),
    path('del/<pk>', SecretariaDeleteView.as_view(), name='del'),
]

solicita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from solicitacao.views import password_reset_request

urlpatterns = [
    path('__admin___/', admin.site.urls),
    path('perfil/', include('perfil.urls')),
    path('produto/', include('produto.urls')),
    path('prefeitura/', include('prefeitura.urls')),
    path('secretaria/', include('secretaria.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/templates/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/templates/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/templates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/templates/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('', include('solicitacao.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

solicitacao/urls.py
from django.urls import path

from .views import (SolicitacaoCreateView, SolicitacaoDeleteView,
                    SolicitacaoDetailView, SolicitacaoDOCX, SolicitacaoEdit,
                    SolicitacaoIndex, SolicitacaoPDF, password_reset_request)

app_name = 'solicitacao'

urlpatterns = [
    path('', SolicitacaoIndex.as_view(), name='index'),
    path('solicita/<pk>', SolicitacaoDetailView.as_view(), name='solicita'),
    path('pdf/<pk>', SolicitacaoPDF.as_view(), name='pdf'),
    path('docx/<pk>', SolicitacaoDOCX.as_view(), name='doc'),
    path('add/', SolicitacaoCreateView.as_view(), name='add'),
    path('edit/<pk>', SolicitacaoEdit.as_view(), name='edit'),
    path('del/<pk>', SolicitacaoDeleteView.as_view(), name='del'),
]

templates/partials/_aside.html
{% load static %}
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->

templates/partials/_footer.html
{% load static %}
{% load filters %}
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-<script>var ano = new Date(); document.write(ano.getFullYear());</script> Created by <a href="mailto:icarodavi@gmail.com">Ícaro Monteiro</a>.</strong> All rights reserved.
</footer>
<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
{% comment %}
<script src="../../dist/js/demo.js"></script> {% endcomment %}

<!-- Page specific script -->
<!-- DataTables  & Plugins -->
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
<script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
<script>
  $(function () {
    $("#tabela").DataTable({
      "responsive": true,
      "lengthChange": false,
      "autoWidth": true,
      "paging": false,
      "searching": false,
      "info": false,
      "responsive": true,
      "ordering": true
      //"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
    }).container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    $('#example2').DataTable({
      "paging": false,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": false,
      "autoWidth": true,
      "responsive": true,
    });
  });
</script>
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
<link rel="stylesheet"
  href="https://cdn.jsdelivr.net/npm/@ttskch/select2-bootstrap4-theme@x.x.x/dist/select2-bootstrap4.min.css">
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

{% if form.media %}
{{form.media}}
{% endif %}
{% if '/add' in request.path or '/edit' in request.path %}
<script>
  $(function () {
    $('select#id_secretaria').select2({
      placeholder: 'Selecione uma secretaria',
      theme: 'bootstrap4'
    });
  });
</script>
<script>
  /*$(function () {
    $('input#id_data').datetimepicker({
      format: 'L'
    });
  });*/
</script>
{% endif %}

templates/partials/_head.html
{% load static %}
{% load filters %}
<link rel="stylesheet" href="{% static 'dist/css/autoComplete.01.min.css' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'icon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'icon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'icon/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'icon/site.webmanifest' %}">
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
{% comment %} <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"> {% endcomment %}
<script src="https://kit.fontawesome.com/c3b1aaf2c0.js" crossorigin="anonymous"></script>
<script src="{% static 'debug_toolbar/js/utils.js' %}"></script>
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
<!-- Theme style -->
    <link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">


<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
<script src="https://cdn.jsdelivr.net/npm/@tarekraafat/autocomplete.js@10.2.6/dist/autoComplete.min.js"></script>

templates/partials/_inicial.html
{% load static %}
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0"> Top Navigation <small>Example 3.0</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="#">Home</a></li>
          <li class="breadcrumb-item"><a href="#">Layout</a></li>
          <li class="breadcrumb-item active">Top Navigation</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-6">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>

            <p class="card-text">
              Some quick example text to build on the card title and make up the bulk of the card's
              content.
            </p>

            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div>

        <div class="card card-primary card-outline">
          <div class="card-body">
            <h5 class="card-title">Card title</h5>

            <p class="card-text">
              Some quick example text to build on the card title and make up the bulk of the card's
              content.
            </p>
            <a href="#" class="card-link">Card link</a>
            <a href="#" class="card-link">Another link</a>
          </div>
        </div><!-- /.card -->
      </div>
      <!-- /.col-md-6 -->
      <div class="col-lg-6">
        <div class="card">
          <div class="card-header">
            <h5 class="card-title m-0">Featured</h5>
          </div>
          <div class="card-body">
            <h6 class="card-title">Special title treatment</h6>

            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>

        <div class="card card-primary card-outline">
          <div class="card-header">
            <h5 class="card-title m-0">Featured</h5>
          </div>
          <div class="card-body">
            <h6 class="card-title">Special title treatment</h6>

            <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
            <a href="#" class="btn btn-primary">Go somewhere</a>
          </div>
        </div>
      </div>
      <!-- /.col-md-6 -->
    </div>
    <!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content -->
</div>
<!-- /.content-wrapper -->

templates/partials/_nav_left.html
{% load static %}
{% load filters %}
<!-- Navbar -->
<nav class="main-header navbar navbar-expand-md navbar-light navbar-white">
  <div class="container">
    <a href="{% url 'solicitacao:index' %}" class="navbar-brand">
      <img src="{% static 'icon/apple-touch-icon.png' %}" alt="Solicitações v 1.0"
        class="brand-image img-circle elevation-0" style="opacity: .8; width: 30px;">
      <!-- LOGO -->
      {% comment %} <i class="fas fa-file"></i> {% endcomment %}
      <!-- <ion-icon name="document-text-outline"></ion-icon> -->
      <span class="brand-text font-weight-light">Solicitações</span>
    </a>

    <button class="navbar-toggler order-1" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse order-3" id="navbarCollapse">
      <!-- Left navbar links -->
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'solicitacao:index' %}" class="nav-link">Início</a>
        </li>
        <li class="nav-item">
          {% comment %} <a href="#" class="nav-link">
            Suporte
          </a> {% endcomment %}
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item dropdown">
          <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
            class="nav-link dropdown-toggle">Sistema</a>
          <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
            <!-- <li><a href="#" class="dropdown-item">Alterar Perfil</a></li> -->
            <li><a href="{% url 'solicitacao:add' %}" class="dropdown-item">Adicionar Solicitação
            </a></li>
            <li class="dropdown-divider"></li>
            <!-- Level two dropdown-->
            <li class="dropdown-submenu dropdown-hover">
              <a id="dropdownSubMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" class="dropdown-item dropdown-toggle">Produtos</a>
              <ul aria-labelledby="dropdownSubMenu2" class="dropdown-menu border-0 shadow">
                <li><a href="{% url 'produto:add' %}" class="dropdown-item">Adicionar Produto</a></li>
                <li>
                  <a tabindex="-1" href="{% url 'produto:index' %}" class="dropdown-item">Listar Produtos</a>
                </li>
              </ul>
            </li>
            <!-- End Level two -->
            <li class="dropdown-submenu dropdown-hover">
              <a id="dropdownSubMenu3" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" class="dropdown-item dropdown-toggle">Prefeituras</a>
              <ul aria-labelledby="dropdownSubMenu3" class="dropdown-menu border-0 shadow">
                <li>
                  <a tabindex="-1" href="{% url 'prefeitura:add' %}" class="dropdown-item">Adicionar Prefeituras</a>
                </li>
                <li>
                  <a tabindex="-1" href="{% url 'prefeitura:index' %}" class="dropdown-item">Listar Prefeituras</a>
                </li>
              </ul>
              <li class="dropdown-submenu dropdown-hover">
                <a id="dropdownSubMenu3" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                  aria-expanded="false" class="dropdown-item dropdown-toggle">Secretarias</a>
                <ul aria-labelledby="dropdownSubMenu3" class="dropdown-menu border-0 shadow">
                  <li><a href="{% url 'secretaria:add' %}" class="dropdown-item">Adicionar Secretaria</a></li>
                  <li><a href="{% url 'secretaria:index' %}" class="dropdown-item">Listar Secretarias</a></li>
                </ul>
              </li>
            </li>
            <li class="dropdown-submenu dropdown-hover">
              <a id="dropdownSubMenu2" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                aria-expanded="false" class="dropdown-item dropdown-toggle">Solicitações</a>
              <ul aria-labelledby="dropdownSubMenu2" class="dropdown-menu border-0 shadow">
                <li>
                  <a tabindex="-1" href="{% url 'solicitacao:add' %}" class="dropdown-item">Adicionar Solicitações</a>
                </li>
                <li>
                  <a tabindex="-1" href="{% url 'solicitacao:index' %}" class="dropdown-item">Listar Solicitações</a>
                </li>
              </ul>
            </li>
          </ul>
        </li>
        {% endif %}
      </ul>

      <!-- SEARCH FORM 
        <form class="form-inline ml-0 ml-md-3">
          <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
              <button class="btn btn-navbar" type="submit">
                <i class="fas fa-search"></i>
              </button>
            </div>
          </div>
        </form>
      </div>-->

templates/partials/_nav_right.html
{% load static %}
<!-- Right navbar links -->
{% if request.user.is_authenticated %}
<ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto">
  <!-- Messages Dropdown Menu -->
  <li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
      <i class="fa-solid fa-circle-user"></i> {{request.user.first_name}} <i class="fa-solid fa-angle-down"></i>
      {% comment %} <span class="badge badge-danger navbar-badge">3</span> {% endcomment %}
    </a>
    <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
      <!-- <li><a href="#" class="dropdown-item">Alterar Perfil</a></li> -->
      {% comment %} <li><a href="#" class="dropdown-item">Alterar dados</a></li>
      <li class="dropdown-divider"></li> {% endcomment %}
      <li><a href="{% url 'password_reset' %}" class="dropdown-item">Alterar senha</a></li>
      <li class="dropdown-divider"></li>
      <li><a href="{% url 'perfil:logout' %}" class="dropdown-item">Sair do Sistema</a></li>
    </ul>
  </li>
  
  {% comment %}
  <li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
      <i class="fas fa-comments"></i>
      <span class="badge badge-danger navbar-badge">3</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
      <a href="#" class="dropdown-item">
        <!-- Message Start -->
        <div class="media">
          <img src="{% static 'dist/img/user1-128x128.jpg' %}" alt="User Avatar" class="img-size-50 mr-3 img-circle">
          <div class="media-body">
            <h3 class="dropdown-item-title">
              Brad Diesel
              <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
            </h3>
            <p class="text-sm">Call me whenever you can...</p>
            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
          </div>
        </div>
        <!-- Message End -->
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item">
        <!-- Message Start -->
        <div class="media">
          <img src="{% static 'dist/img/user8-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
          <div class="media-body">
            <h3 class="dropdown-item-title">
              John Pierce
              <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
            </h3>
            <p class="text-sm">I got your message bro</p>
            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
          </div>
        </div>
        <!-- Message End -->
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item">
        <!-- Message Start -->
        <div class="media">
          <img src="{% static 'dist/img/user3-128x128.jpg' %}" alt="User Avatar" class="img-size-50 img-circle mr-3">
          <div class="media-body">
            <h3 class="dropdown-item-title">
              Nora Silvester
              <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
            </h3>
            <p class="text-sm">The subject goes here</p>
            <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
          </div>
        </div>
        <!-- Message End -->
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
    </div>
  </li>
   <!-- Notifications Dropdown Menu -->
  <li class="nav-item dropdown">
    <a class="nav-link" data-toggle="dropdown" href="#">
      <i class="far fa-bell"></i>
      <span class="badge badge-warning navbar-badge">15</span>
    </a>
    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
      <span class="dropdown-header">15 Notifications</span>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item">
        <i class="fas fa-envelope mr-2"></i> 4 new messages
        <span class="float-right text-muted text-sm">3 mins</span>
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item">
        <i class="fas fa-users mr-2"></i> 8 friend requests
        <span class="float-right text-muted text-sm">12 hours</span>
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item">
        <i class="fas fa-file mr-2"></i> 3 new reports
        <span class="float-right text-muted text-sm">2 days</span>
      </a>
      <div class="dropdown-divider"></div>
      <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
    </div>
  </li>
  <!--  <li class="nav-item">
    <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
      <i class="fas fa-th-large"></i>
    </a>
  </li>--> {% endcomment %}
</ul>
{% endif %}
</div>
</nav>
<!-- /.navbar -->

templates/partials/_pagination.html
{% if is_paginated %}
<div class="row mt-3">
    <div class="col">                
        <div class="pagination">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page=1">&laquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&lsaquo;</a>
                </li>
                {% endif %}

                {% for num in page_obj.paginator.page_range %}

                {% if page_obj.number == num %}
                <li class="page-item active">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
                {% endif %}

                {% endfor %}

                {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">&rsaquo;</a>
                </li>
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">&raquo;</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endif %}