perfil/urls.py
from django.urls import path
from .views import Login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/index.html'), name='index'),
    path('login/', LoginView.as_view(
        template_name='perfil/index.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

secretaria/urls.py
from django.urls import path
from .views import SecretariaListView, SecretariaCreateView, SecretariaEdit, SecretariaDeleteView

app_name = 'secretaria'

urlpatterns = [
    path('', SecretariaListView.as_view(), name='index'),
    path('add/', SecretariaCreateView.as_view(), name='add'),
    path('edit/<pk>', SecretariaEdit.as_view(), name='edit'),
    path('del/<pk>', SecretariaDeleteView.as_view(), name='del'),
]

solicita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from solicitacao.views import password_reset_request

urlpatterns = [
    path('__admin___/', admin.site.urls),
    path('perfil/', include('perfil.urls')),
    path('produto/', include('produto.urls')),
    path('prefeitura/', include('prefeitura.urls')),
    path('secretaria/', include('secretaria.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/templates/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/templates/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/templates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/templates/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('', include('solicitacao.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

secretaria/models.py
from django.db import models
from prefeitura.models import Prefeitura
# Create your models here.


class Secretaria(models.Model):
    nome = models.CharField(max_length=100)
    prefeitura = models.ForeignKey(Prefeitura, on_delete=models.CASCADE)
    endereco = models.CharField(max_length=200)
    secretario = models.CharField(max_length=120)
    ativo = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.nome} - {self.prefeitura}'

    def get_nome(self):
        return f'{self.prefeitura} - {self.nome}'

    def get_nome_secretaria(self):
        return f'{self.nome} - {self.prefeitura}'

    def get_logotipo(self):
        return self.prefeitura.logotipo.url

secretaria/forms.py
from django import forms
from .models import Secretaria


class SecretariaForm(forms.ModelForm):

    class Meta:
        model = Secretaria
        fields = '__all__'

secretaria/views.py
import django
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views import View
from django.views.generic import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from .models import Secretaria
from .forms import SecretariaForm


class SecretariaListView(LoginRequiredMixin, ListView):
    model = Secretaria
    template_name = "secretaria/index.html"
    context_object_name = 'secretarias'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.select_related('prefeitura')
        return qs


class SecretariaCreateView(LoginRequiredMixin, View):
    model = Secretaria
    template_name = 'secretaria/form.html'
    fields = '__all__'
    success_url = 'secretaria:index'

    def get(self, *args, **kwargs):
        form = SecretariaForm()
        return render(self.request, 'secretaria/form.html', {'form': form})

    def post(self, *args, **kwargs):
        form = SecretariaForm(data=self.request.POST, files=self.request.FILES)
        if form.is_valid():
            form.save()
            return redirect('secretaria:index')
        else:
            return render(self.request, 'secretaria/form.html', {'form': form})


class SecretariaEdit(LoginRequiredMixin, UpdateView):
    model = Secretaria
    template_name = 'secretaria/edit.html'
    fields = '__all__'
    success_url = reverse_lazy('secretaria:index')


class SecretariaDeleteView(LoginRequiredMixin, DeleteView):
    model = Secretaria
    template_name = "secretaria/delete.html"
    success_url = reverse_lazy('secretaria:index')

secretaria/templates/secretaria/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}| Listagem de Secretarias{% endblock titulo %}
{% block conteudo %}
<div class="wrapper">
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2 d-flex-inline justify-content-between">
            <div class="col">
              <h1>Secretaria</h1>
            </div>
            <div class="col d-flex justify-content-end">
              <a href="{% url 'secretaria:add' %}" class="btn btn-info"><i class="fa fa-add"></i> Criar Secretaria</a>
            </div>
          
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
           <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listagem das Secretarias</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tabela" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Secretaria</th>
                    <th>Secretário(a)</th>
                    <th>Prefeitura</th>
                    <th>Ações</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for secretaria in secretarias %}
                  <tr>
                    <td>{{secretaria.id}}</td>
                    <td>{{secretaria.get_nome_secretaria}}</td>
                    <td>{{secretaria.secretario}}</td>
                    <td>{{secretaria.prefeitura.get_prefeitura}}</td>
                    <td>
                      <ul class="navbar-nav navbar-no-expand ml-2">
                        <li class="nav-item ml-2"><a href="{% url 'secretaria:edit' secretaria.id %}" class="btn btn-primary"><i class="fas fa-pen-to-square"></i></a></li>
                        <li class="nav-item ml-2"><a href="{% url 'secretaria:del' secretaria.id %}" class="btn btn-danger"><i class="fas fa-trash-can"></i></a></li>
                      </ul>
                    
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Secretaria</th>
                    <th>Secretário(a)</th>
                    <th>Prefeitura</th>
                    <th>Ações</th>
                  </tr>
                  </tfoot>
                </table>
                <div class="row">
                  <div class="col d-flex align-content-center">
                    {% include 'partials/_pagination.html' %}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
</div>
{% endblock conteudo %}