perfil/urls.py
from django.urls import path
from .views import Login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/index.html'), name='index'),
    path('login/', LoginView.as_view(
        template_name='perfil/index.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

solicita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from solicitacao.views import password_reset_request

urlpatterns = [
    path('__admin___/', admin.site.urls),
    path('perfil/', include('perfil.urls')),
    path('produto/', include('produto.urls')),
    path('prefeitura/', include('prefeitura.urls')),
    path('secretaria/', include('secretaria.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/templates/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/templates/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/templates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/templates/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('', include('solicitacao.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

solicitacao/urls.py
from django.urls import path

from .views import (SolicitacaoCreateView, SolicitacaoDeleteView,
                    SolicitacaoDetailView, SolicitacaoDOCX, SolicitacaoEdit,
                    SolicitacaoIndex, SolicitacaoPDF, password_reset_request)

app_name = 'solicitacao'

urlpatterns = [
    path('', SolicitacaoIndex.as_view(), name='index'),
    path('solicita/<pk>', SolicitacaoDetailView.as_view(), name='solicita'),
    path('pdf/<pk>', SolicitacaoPDF.as_view(), name='pdf'),
    path('docx/<pk>', SolicitacaoDOCX.as_view(), name='doc'),
    path('add/', SolicitacaoCreateView.as_view(), name='add'),
    path('edit/<pk>', SolicitacaoEdit.as_view(), name='edit'),
    path('del/<pk>', SolicitacaoDeleteView.as_view(), name='del'),
]

solicitacao/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _
from produto.models import Produto
from secretaria.models import Secretaria


class Solicitacao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    objeto = models.TextField('Objeto', blank=True,  null=True)
    secretaria = models.ForeignKey(Secretaria, on_delete=models.DO_NOTHING)
    data = models.DateField('Data')
    status = models.CharField(default='P', max_length=1, choices=(
        ('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'),
        ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado'),))

    def __str__(self):
        return f'Solicitação nº {self.pk}'

    class Meta:
        verbose_name = 'Solicitação'
        verbose_name_plural = 'Solicitações'
        ordering = ['-id']


class SolicitacaoItem(models.Model):
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.CASCADE)
    soliticao_item = models.ManyToManyField(
        Solicitacao, related_name='solicitacao', through='SolicitacaoQuantidade')
    produto = models.CharField(_('Produto'), max_length=255)
    produto_id = models.PositiveIntegerField(_('Produto_ID'), )
    qtd = models.PositiveIntegerField(
        _('Quantidade'), blank=True, null=True)
    imagem = models.CharField(
        _("Imagem"), max_length=2000, blank=True, null=True)

    def __str__(self):
        return self.produto

    def get_nome(self):
        return f'{self.produto}'

    def get_unidade(self):
        unidade = Produto.objects.get(pk=self.produto_id).values('unidade')
        return f'{unidade}'

    class Meta:
        verbose_name = 'Item da Solicitação'
        verbose_name_plural = 'Itens da Solicitação'


class SolicitacaoQuantidade(models.Model):
    solicitacao = models.ForeignKey(
        Solicitacao, on_delete=models.CASCADE, related_name='quantidade')
    item_solicitacao = models.ForeignKey(
        SolicitacaoItem, on_delete=models.CASCADE, related_name='quantidade')
    # quantidade = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.solicitacaoitem.produto} - Qtd: {self.quantidade}'

    class Meta:
        verbose_name = 'Through Quantidade'
        verbose_name_plural = 'Through Quantidades'

solicitacao/forms.py
from django.contrib.auth.models import User
from django.forms import DateField, DateInput, ModelForm
from tempus_dominus.widgets import DatePicker

from .models import Solicitacao


class SolicitacaoForm(ModelForm):

    data = DateField(
        input_formats=['%d/%m/%Y'],
        widget=DatePicker(
            attrs={
                # 'class': 'form-control datetimepicker-input',
                # 'data-target': '#id_data'
                'append': 'fa fa-calendar',
                'icon_toggle': True
            },
        ),
        required=False)

    class Meta:
        model = Solicitacao
        fields = '__all__'
        exclude = ('usuario', 'qtd_total',)


class PasswordResetForm(ModelForm):

    class Meta:
        model = User
        fields = ('email',)
        # exclude = ('password', 'las_login')

solicitacao/views.py
import os
import tempfile
from datetime import datetime
from pprint import pprint

from decouple import config
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.core.mail import BadHeaderError, send_mail
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.template.loader import get_template, render_to_string
from django.urls import reverse, reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.views.generic import (CreateView, DeleteView, DetailView,
                                  UpdateView, View)
from django.views.generic.list import ListView
from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from htmldocx import HtmlToDocx
from secretaria.models import Secretaria
from solicita.storage_backends import PublicMediaStorage
from xhtml2pdf import pisa

from .forms import PasswordResetForm, SolicitacaoForm
from .models import Solicitacao


class SolicitacaoIndex(LoginRequiredMixin, ListView):
    model = Solicitacao
    template_name = 'solicitacao/index.html'
    context_object_name = 'solicitacoes'
    paginate_by = 10

    def get_queryset(self):
        query_set = super().get_queryset()
        query_set = query_set.select_related('secretaria')
        return query_set

    class Meta:
        ordering = ['-id']


class SolicitacaoDetailView(LoginRequiredMixin, DetailView):
    model = Solicitacao
    template_name = "solicitacao/solicitacao.html"
    context_object_name = 'solicitacao'


class SolicitacaoPDF(LoginRequiredMixin, View):
    model = Solicitacao
    template_name = 'solicitacao/render_pdf.html'
    context_object_name = 'solicitacao'

    def get(self, *args, **kwargs):
        template_path = self.template_name
        solicitacao = Solicitacao.objects.filter(pk=kwargs.get('pk'))
        solicitacao = solicitacao.select_related('secretaria').first()
        context = {'solicitacao': solicitacao}
        # Create a Django response object, and specify content_type as pdf
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="report.pdf"'
        # find the template and render it.
        template = get_template(template_path)
        html = template.render(context)
        # create a pdf
        pisa_status = pisa.CreatePDF(
            html, dest=response)
        # if error then show some funny view
        if pisa_status.err:
            return HttpResponse('We had some errors <pre>' + html + '</pre>')
        return response


class SolicitacaoDOCX(LoginRequiredMixin, View):
    model = Solicitacao
    template_name = 'solicitacao/render_doc.html'
    context_object_name = 'solicitacao'

    def get(self, *args, **kwargs):
        template_path = self.template_name
        solicitacao = Solicitacao.objects.filter(pk=kwargs.get('pk'))
        solicitacao = solicitacao.select_related('secretaria').first()
        context = {'solicitacao': solicitacao}
        template = get_template(template_path)
        html = template.render(context)
        media_storage: PublicMediaStorage = PublicMediaStorage()
        default_doc: PublicMediaStorage = media_storage.open('default.docx')
        document: Document = Document(docx=default_doc)
        docx: HtmlToDocx = HtmlToDocx()
        docx.add_html_to_document(html, document)
        # pprint(dir(solicitacao.first().secretaria.prefeitura.get_logo))
        # pprint(vars(solicitacao.first().secretaria.prefeitura.get_logo))
        section = document.sections[0]
        header = section.header
        # paragraph = header.paragraphs[0]
        # paragraph.add_picture(
        #     solicitacao.first().secretaria.prefeitura.get_logo)
        # paragraph.text = '\t{}'.format(solicitacao.secretaria.prefeitura)
        # document.add_picture(solicitacao.secretaria.prefeitura.get_logo())
        header_table = header.add_table(1, 2, Inches(6))
        header_table_cells = header_table.rows[0].cells
        header_table_0 = header_table_cells[0].add_paragraph()
        kh = header_table_0.add_run()
        kh.add_picture(
            solicitacao.secretaria.prefeitura.get_logo(), width=Inches(1))
        header_table_1 = header_table_cells[1].add_paragraph(
            solicitacao.secretaria.prefeitura.get_prefeitura()+'\n'+solicitacao.secretaria.nome+'\n'+solicitacao.secretaria.endereco)
        header_table_1.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        # p2 = header.paragraphs[1]
        # p2.text = solicitacao.secretaria.nome
        tempdir = tempfile.mkdtemp()
        document.save(os.path.join(tempdir, 'report.docx'))
        with open(os.path.join(tempdir, 'report.docx'), "rb") as doc_ok:
            response: HttpResponse = HttpResponse(doc_ok,
                                                  content_type='application/docx')
            response['Content-Disposition'] = 'attachment; filename="report.docx"'
        return response


class SolicitacaoCreateView(LoginRequiredMixin, View):
    model = Solicitacao
    template_name = 'solicitacao/form.html'
    fields = '__all__'
    success_url = 'produto:busca'

    def get(self, *args, **kwargs):
        form = SolicitacaoForm()
        return render(self.request, 'solicitacao/form.html', {'form': form})

    def post(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            user = self.request.user
            data = self.request.POST

            # print(user)
            # self.request.POST['usuario'] = user
            #   'data': ['02/04/2022'], 'status': ['P']}
            dados = {
                'csrfmiddlewaretoken': data['csrfmiddlewaretoken'],
                'objeto': data['objeto'],
                'secretaria': data['secretaria'],
                'data': data['data'],
                'status': data['status'],
            }
            # pprint(dir(user))
            # pprint(vars(user))
        form = SolicitacaoForm(data=self.request.POST,
                               files=self.request.FILES)
        # pprint(dir(form.clean()))
        # pprint(vars(form.clean()))
        secretaria = Secretaria.objects.filter(pk=data['secretaria']).first()
        if form.is_valid():
            solicitacao = Solicitacao(
                usuario=user,
                objeto=data['objeto'],
                secretaria=secretaria,
                data=datetime.strptime(data['data'], '%d/%m/%Y'),
                status=data['status']
            )
            solicitacao.save()
            # form.save(commit=False)
            # form.user = user.User
            # pprint(dir(form))
            # pprint(vars(form))
            # form.save()
            return redirect(reverse('produto:busca', kwargs={'pk': solicitacao.pk}))
        else:
            return render(self.request, 'solicitacao/form.html', {'form': form})


class SolicitacaoEdit(LoginRequiredMixin, UpdateView):
    model = Solicitacao
    template_name = 'solicitacao/edit.html'
    # fields = '__all__'
    form_class = SolicitacaoForm
    # success_url = redirect('produto:busca' self)

    # def post(self, request: HttpRequest, *args: Any, **kwargs: Any) -> HttpResponse:
    #     #  redirect('produto:busca', kwargs={'pk': kwargs.get('pk')})
    #     return super().post(request, *args, **kwargs)

    def get_success_url(self, *args, **kwargs) -> str:
        x = self.kwargs.get('pk')
        return reverse('produto:busca', args=[x])


class SolicitacaoDeleteView(LoginRequiredMixin, DeleteView):
    model = Solicitacao
    template_name = "produto/delete.html"
    success_url = reverse_lazy('produto:index')


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Requisição para resetar senha - Solicitações App"
                    email_template_name = "password/templates/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        # 'domain': '127.0.0.1:8000',
                        'domain': config('DOMAIN_URL'),
                        'site_name': 'Solicitação v1.0',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': config('DOMAIN_PROTOCOL'),
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'icarodavi@gmail.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("/password_reset/done/")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="password/templates/password_reset.html", context={"password_reset_form": password_reset_form})

solicitacao/templates/solicitacao/delete.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}| Listagem de Prefeituras{% endblock titulo %}
{% block conteudo %}
<div class="wrapper">
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <div class="container-fluid">
                <div class="row mb-2">
                    <div class="col-sm-6">
                        <h1>Prefeituras</h1>
                    </div>
                </div>
            </div><!-- /.container-fluid -->
        </section>

        <!-- Main content -->
        <section class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Deletar Prefeitura</h3>
                            </div>
                            <!-- /.card-header -->
                            <div class="card-body">
                                <form method="post">{% csrf_token %}
                                    <p>Você quer realmente deletar: "{{ object }}"?</p>
                                    {{ form|crispy }}
                                    <input type="submit" class="btn btn-danger" value="Confirma">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock %}

solicitacao/templates/solicitacao/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}| Listagem de Solicitações{% endblock titulo %}
{% block conteudo %}
<div class="wrapper">
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2 d-flex-inline justify-content-between">
            <div class="col">
              <h1>Solicitações</h1>
            </div>
            <div class="col d-flex justify-content-end">
              <a href="{% url 'solicitacao:add' %}" class="btn btn-info"><i class="fa fa-add"></i> Criar Solicitação</a>
            </div>
          
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
           <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listagem das solicitações</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tabela" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Secretaria</th>
                    <th>Objeto</th>
                    <th>Data</th>
                    {% comment %} <th>Total de Itens</th> {% endcomment %}
                    <th>Status</th>
                    <th>Ações</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for solicitacao in solicitacoes %}
                  <tr>
                    <td>{{solicitacao.id}}</td>
                    <td><a href="{% url 'solicitacao:edit' solicitacao.id %}">{{solicitacao.secretaria.get_nome}}</a></td>
                    <td>{{solicitacao.objeto}}</td>
                    <td>{{solicitacao.data}}</td>
                    <td>{{solicitacao.get_status_display}}</td>
                    <td>
                      <div class="navbar-collapse">
                      <ul class="navbar-nav navbar-no-expand ml-2">
                        <li class="nav-item dropdown">
                          <a id="dropdownSubMenu1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
                            class="nav-item dropdown-toggle btn btn-secondary">
                            <i class="fa-solid fa-file-export"></i>
                            Gerar</a>
                          <ul aria-labelledby="dropdownSubMenu1" class="dropdown-menu border-0 shadow">
                            <li><a href="{% url 'solicitacao:pdf' solicitacao.id %}" class="dropdown-item"><i class="fa-solid fa-file-pdf"></i> PDF</a></li>
                            <li><a href="{% url 'solicitacao:doc' solicitacao.id %}" class="dropdown-item"><i class="fa-solid fa-file-word"></i> Word</a></li>
                          </ul>
                          <li class="nav-item ml-2"><a href="{% url 'solicitacao:edit' solicitacao.id %}" class="btn btn-primary"><i class="fas fa-pen-to-square"></i></a></li>
                          <li class="nav-item ml-2"><a href="{% url 'solicitacao:del' solicitacao.id %}" class="btn btn-danger"><i class="fas fa-trash-can"></i></a></li>
                      </ul>
                    </div>
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Secretaria</th>
                    <th>Objeto</th>
                    <th>Data</th>
                    <th>Status</th>
                    <th>Ações</th>
                  </tr>
                  </tfoot>
                </table>
                <div class="row">
                  <div class="col d-flex align-content-center">
                    {% include 'partials/_pagination.html' %}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
</div>

{% endblock conteudo %}

solicitacao/templates/solicitacao/render_doc.html
{% load filters %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RenderPDF</title>
    {% load static %}
<link rel="apple-touch-icon" sizes="180x180" href="{%static 'icon/apple-touch-icon.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{%static 'icon/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{%static 'icon/favicon-16x16.png' %}">
<link rel="manifest" href="{%static 'icon/site.webmanifest' %}">
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
{% comment %} <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}"> {% endcomment %}
<script src="https://kit.fontawesome.com/c3b1aaf2c0.js" crossorigin="anonymous"></script>
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">


<!-- DataTables -->
<link rel="stylesheet" href="{% static 'plugins/datatables-bs4/css/dataTables.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-responsive/css/responsive.bootstrap4.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/datatables-buttons/css/buttons.bootstrap4.min.css' %}">
</head>
<body>
    <div id="header_content" style="text-align:center">
        {% comment %} <img src="{{solicitacao.secretaria.prefeitura.logotipo.name|s3url_media}}" style="width:80px;"> {% endcomment %}
        {% comment %} <img src="{{solicitacao.secretaria.get_logotipo.name|s3url_media}}" style="width:80px;"> {% endcomment %}
        <p>{{solicitacao.secretaria.get_nome}}</p>
        <p>{{solicitacao.secretaria.endereco}}</p>
    </div>
    <h1>Solicitação nº {{solicitacao.id}}</h1>
    <table id="tabela" class="table table-bordered table-striped">
        <thead>
            <tr>
                <td>Solicitação</td>
                <td>Imagem</td>
                <td>Produto</td>
                <td>Ref. Produto</td>
            </tr>
        </thead>
        <tbody>
    {% for item in solicitacao.solicitacaoitem_set.all %}
    <tr>
        <td>{{item.solicitacao}}</td>
        <td>{{item.imagem}}</td>
        <td>{{item.produto}}</td>
        <td>{{item.produto_id}}</td>
    </tr>
  {% endfor %}
</tbody>
</table>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>

</body>
</html>

solicitacao/templates/solicitacao/render_pdf.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RenderPDF</title>
    <style>
        @page {
            size: a4 portrait;
            @frame header_frame {           /* Static Frame */
                -pdf-frame-content: header_content;
                left:50pt; width: 512pt; top: 10pt; height: 100pt;
            }
            @frame content_frame {          /* Content Frame */
                left: 50pt; width: 512pt; top: 90pt; height: 632pt;
            }
        }
    </style>
    {% load static %}
    {% load filters %}

</head>
<body>
    <div id="header_content" style="text-align:center">
        {% comment %} <img src="{{solicitacao.secretaria.get_logotipo.name|s3url_media}}" style="width:80px;"> {% endcomment %}
        <img src="{{solicitacao.secretaria.prefeitura.get_logo}}" style="width:80px;"> 
        <p>{{solicitacao.secretaria.get_nome}}</p>
        <p>{{solicitacao.secretaria.endereco}}</p>
    </div>
    <h1>Solicitação nº {{solicitacao.id}}</h1>
    
    <table id="tabela" class="table table-bordered table-striped">
        <thead>
            <tr>
                <td>01</td>
                <td>02</td>
                <td>03</td>
                <td>04</td>
            </tr>
        </thead>
        <tbody>
    {% for item in solicitacao.solicitacaoitem_set.all %}
    <tr>
        <td>{{item.solicitacao}}</td>
        <td>{{item.imagem}}</td>
        <td>{{item.produto}}</td>
        <td>{{item.produto_id}}</td>
    </tr>
  {% endfor %}
</tbody>
</table>
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE for demo purposes -->
{% comment %} <script src="../../dist/js/demo.js"></script> {% endcomment %}

<!-- Page specific script -->
  <!-- DataTables  & Plugins -->
  <script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-responsive/js/dataTables.responsive.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-responsive/js/responsive.bootstrap4.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-buttons/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-buttons/js/buttons.bootstrap4.min.js' %}"></script>
  <script src="{% static 'plugins/jszip/jszip.min.js' %}"></script>
  <script src="{% static 'plugins/pdfmake/pdfmake.min.js' %}"></script>
  <script src="{% static 'plugins/pdfmake/vfs_fonts.js' %}"></script>
  <script src="{% static 'plugins/datatables-buttons/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-buttons/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'plugins/datatables-buttons/js/buttons.colVis.min.js' %}"></script>
  <script>
      $(function () {
        $("#tabela").DataTable({
          "responsive": true, 
          "lengthChange": false, 
          "autoWidth": true, 
          "paging":false,
          "searching":false, 
          "info":false,
          "responsive":true,
          "ordering":true
          //"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
          "paging": false,
          "lengthChange": false,
          "searching": false,
          "ordering": true,
          "info": false,
          "autoWidth": true,
          "responsive": true,
        });
      });
    </script>
</body>
</html>