perfil/urls.py
from django.urls import path
from .views import Login
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'perfil'

urlpatterns = [
    path('', LoginView.as_view(template_name='perfil/index.html'), name='index'),
    path('login/', LoginView.as_view(
        template_name='perfil/index.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

produto/urls.py
from django.urls import path
from .views import ProdutoList, ProdutoCreateView, ProdutoEdit
from .views import ProdutoDeleteView, ProdutoSearch, generate_data, Buscador
from .views import Blank

app_name = 'produto'

urlpatterns = [
    path('',  ProdutoList.as_view(), name='index'),
    path('add/', ProdutoCreateView.as_view(), name='add'),
    path('edit/<pk>', ProdutoEdit.as_view(), name='edit'),
    path('del/<pk>', ProdutoDeleteView.as_view(), name='del'),
    path('search/', ProdutoSearch.as_view(), name='search'),
    path('busca/<pk>', Buscador.as_view(), name='busca'),
    path('blank', Blank.as_view(), name='blank'),
    # path('gera/', generate_data, name='gera')
]

solicita/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from solicitacao.views import password_reset_request

urlpatterns = [
    path('__admin___/', admin.site.urls),
    path('perfil/', include('perfil.urls')),
    path('produto/', include('produto.urls')),
    path('prefeitura/', include('prefeitura.urls')),
    path('secretaria/', include('secretaria.urls')),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('password_reset/templates/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='password/templates/password_reset_done.html'), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name="password/templates/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password/templates/password_reset_complete.html'), name='password_reset_complete'),
    path("password_reset/", password_reset_request, name="password_reset"),
    path('', include('solicitacao.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

produto/models.py
from django.db import models
from django.utils.text import slugify

# from utils.resize import resize_image


class Produto(models.Model):
    nome = models.CharField(max_length=255)
    descricao_curta = models.TextField(max_length=255)
    descricao_longa = models.TextField()
    unidade = models.CharField(max_length=30, default='UN')
    imagem = models.ImageField(
        upload_to='produto_imagens/%Y/%m', blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)

    def __str__(self):
        return f'{self.nome}'

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = slugify(self.nome)
            self.slug = slug
        super().save(*args, **kwargs)

solicitacao/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import gettext as _
from produto.models import Produto
from secretaria.models import Secretaria


class Solicitacao(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    objeto = models.TextField('Objeto', blank=True,  null=True)
    secretaria = models.ForeignKey(Secretaria, on_delete=models.DO_NOTHING)
    data = models.DateField('Data')
    status = models.CharField(default='P', max_length=1, choices=(
        ('A', 'Aprovado'), ('C', 'Criado'), ('R', 'Reprovado'),
        ('P', 'Pendente'), ('E', 'Enviado'), ('F', 'Finalizado'),))

    def __str__(self):
        return f'Solicitação nº {self.pk}'

    class Meta:
        verbose_name = 'Solicitação'
        verbose_name_plural = 'Solicitações'
        ordering = ['-id']


class SolicitacaoItem(models.Model):
    solicitacao = models.ForeignKey(Solicitacao, on_delete=models.CASCADE)
    soliticao_item = models.ManyToManyField(
        Solicitacao, related_name='solicitacao', through='SolicitacaoQuantidade')
    produto = models.CharField(_('Produto'), max_length=255)
    produto_id = models.PositiveIntegerField(_('Produto_ID'), )
    qtd = models.PositiveIntegerField(
        _('Quantidade'), blank=True, null=True)
    imagem = models.CharField(
        _("Imagem"), max_length=2000, blank=True, null=True)

    def __str__(self):
        return self.produto

    def get_nome(self):
        return f'{self.produto}'

    def get_unidade(self):
        unidade = Produto.objects.get(pk=self.produto_id).values('unidade')
        return f'{unidade}'

    class Meta:
        verbose_name = 'Item da Solicitação'
        verbose_name_plural = 'Itens da Solicitação'


class SolicitacaoQuantidade(models.Model):
    solicitacao = models.ForeignKey(
        Solicitacao, on_delete=models.CASCADE, related_name='quantidade')
    item_solicitacao = models.ForeignKey(
        SolicitacaoItem, on_delete=models.CASCADE, related_name='quantidade')
    # quantidade = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f'{self.solicitacaoitem.produto} - Qtd: {self.quantidade}'

    class Meta:
        verbose_name = 'Through Quantidade'
        verbose_name_plural = 'Through Quantidades'

produto/forms.py
from django.forms import ModelForm
from .models import Produto


class ProdutoForm(ModelForm):

    class Meta:
        model = Produto
        fields = '__all__'
        exclude = ('slug',)

produto/views.py
import copy
import itertools
import json
from pprint import pprint

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import DeleteView, UpdateView
from django.views.generic.list import ListView
from faker import Faker
from solicitacao.models import Solicitacao, SolicitacaoItem

from .forms import ProdutoForm
from .models import Produto


class ProdutoList(LoginRequiredMixin, ListView):
    model = Produto
    template_name = 'produto/index.html'
    context_object_name = 'produtos'
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset()
        return qs


class ProdutoCreateView(LoginRequiredMixin, View):
    model = Produto
    template_name = 'produto/form.html'
    fields = '__all__'
    success_url = 'produto:index'

    def get(self, *args, **kwargs):
        form = ProdutoForm()
        return render(self.request, 'produto/form.html', {'form': form})

    def post(self, *args, **kwargs):
        form = ProdutoForm(data=self.request.POST, files=self.request.FILES)
        if form.is_valid():
            form.save()
            return redirect('produto:index')
        else:
            return render(self.request, 'produto/form.html', {'form': form})


class ProdutoEdit(LoginRequiredMixin, UpdateView):
    model = Produto
    template_name = 'produto/edit.html'
    fields = '__all__'
    success_url = reverse_lazy('produto:index')


class ProdutoDeleteView(LoginRequiredMixin, DeleteView):
    model = Produto
    template_name = "produto/delete.html"
    success_url = reverse_lazy('produto:index')


class ProdutoSearch(LoginRequiredMixin, View):
    model = Produto

    def get(self, *args, **kwargs):
        search = self.request.GET['search']
        payload = []
        if search:
            objs: Produto = Produto.objects.filter(nome__icontains=search)
            for item in objs:
                payload.append({
                    'id': item.id,
                    'produto': item.nome,
                    'descricao_curta': item.descricao_curta,
                    'descricao_longa': item.descricao_longa,
                    'imagem': item.imagem.name,
                    'unidade': item.unidade,
                    'delete': False,
                })

        return JsonResponse({
            'status': 200,
            'data': payload
        })


class Buscador(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        solicitacao = Solicitacao.objects.filter(pk=kwargs.get(
            'pk')).first()
        items = SolicitacaoItem.objects.filter(
            solicitacao=solicitacao).values()
        if items:
            contexto = {'solicitacao': solicitacao,
                        'items': json.dumps(list(items))}
        else:
            contexto = {'solicitacao': solicitacao}
        return render(self.request, 'produto/busca.html', context=contexto)

    def post(self, *args, **kwargs):

        data = json.loads(self.request.POST.get('objProdutos'))
        # produtos = {'produtos': data}
        solicitacao = Solicitacao.objects.filter(
            pk=kwargs.get('pk')).first()
        list_data = [SolicitacaoItem(
            solicitacao=solicitacao,
            produto=v['produto'],
            produto_id=v['id'],
            qtd=v['qtd'],
            imagem=v['imagem'],
        ) for v in data]
        solicitacao.solicitacaoitem_set.all().delete()
        solicitacao.solicitacaoitem_set.set(list_data, bulk=False, clear=True)

        # return render(self.request, 'produto/blank.html', context=produtos)
        return redirect('solicitacao:edit', solicitacao.id)


class Blank(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        return render(self.request, 'produto/blank.html')

    def post(self, *args, **kwargs):
        produtos = {'produtos': json.loads(
            self.request.POST.get('objProdutos'))}
        return render(self.request, 'produto/blank.html', context=produtos)


def generate_data(request):
    faker: Faker = Faker('pt_BR')
    for i in range(0, 10):
        Produto.objects.create(
            nome=faker.company(),
            descricao_curta=faker.paragraphs(nb=1),
            descricao_longa=faker.paragraphs(nb=5),
        )
    return JsonResponse({
        'status': 200
    })

produto/templates/produto/blank.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for produto in produtos %}
    <p>{{produto.id}}</p>
    <p>{{produto.nome}}</p>
    <p>{{produto.descricao_curta}}</p>
    <p>{{produto.descricao_longa}}</p>
    <p>{{produto.quantidade}}</p>
    <hr>
    {% endfor %}
    
</body>
</html>

produto/templates/produto/busca.html
{% extends 'base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block titulo %}| Listagem de Prefeituras{% endblock titulo %}
{% block conteudo %}

<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>Criar Solicitação</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Adicionar Solicitação</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table class="table table-hover">
                  <tbody>
                    <tr>
                      <th scope="col">Solicitação</th>
                      <td scope="col">{{solicitacao}}</td>
                    </tr>
                    <tr>
                      <th scope="col">Secretaria</th>
                      <td scope="col">{{solicitacao.secretaria}}</td>
                    </tr>
                    <tr>
                      <th scope="col">Data</th>
                      <td scope="col">{{solicitacao.data}}</td>
                    </tr>
                  </tbody>
                </table>
{{solicitacao}}
                <form method="post" onsubmit="atualiza_obj();" action="{% url 'produto:busca' solicitacao.id %}">{% csrf_token %}
                  <input type="hidden" name="objProdutos" id="objProdutos" 
                  value="">
                  <div class="form-group w-100 ml-2 mt-2">
                    <label for="autoComplete">Produto:</label>
                    <input id="autoComplete" type="text" dir="ltr" spellcheck=false autocorrect="off" autocomplete="off"
                      autocapitalize="off" class="form-control">
                    <small class="form-text text-muted">Escolha seu produto e clique para ser adicionado à
                      solicitação</small>
                  </div>
                  <div class="form-group">
                    <ul id="result" multiple class="list-group list-group-horizontal-xxl">
                      {% for item in solicitacao.solicitacaoitem_set.all %}
                      <li id="li-{{item.id}}" class="list-group-item d-flex p-2 bd-highlight justify-content-between">
                        {{item}}
                        <div class="form-row form-inline">
                          Quantidade: 
                          <input name="quantidade-{{item.id}}" id="quantidade-{{item.id}}" type="number" class="form-text form-control mr-2 ml-2" 
                          onchange="modifica_quantidade({{item.id}})" required value="{{item.qtd}}">
                        <a href="javascript:void(0)" class="btn btn-danger li-produto mr-1" onclick='removerProduto("li-{{item.id}}",{{item.id}})'>
                          <i class="fas fa-trash-can"></i>
                        </a>
                      </div>
                    </li>
                      {% endfor %}
                    </ul>
                  </div>
                  <input type="submit" value="Salvar" class="btn btn-success">

                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    {{items|json_script:'json_data'}}
    <script>
      const resultado = document.getElementById("result");
      const objProdutos = document.getElementById('objProdutos');
      var json_data;
      ob = [];
      const autoCompleteJS = new autoComplete({
        selector: "#autoComplete",
        placeHolder: "Digite um produto...",
        debouce: 300,
        threshold: 3,
        resultsList: {
          maxResults: 10,
        },
        data: {
          src: async (query) => {
            try {
              const source = await fetch(`/produto/search/?search=${query}`);
              const data = await source.json();
              return data.data;
            } catch (error) {
              return error;
            }
          },
          keys: ["produto"],
          cache: false,
        },
        resultsList: {
          element: (list, data) => {
            if (!data.results.length) {
              // Create "No Results" message element
              const message = document.createElement("div");
              // Add class to the created element
              message.setAttribute("class", "no_result");
              // Add message text content
              message.innerHTML = `<span>Sem resultados para "${data.query}"</span>`;
              // Append message element to the results list
              list.prepend(message);
            }
          },
          noResults: true,
        },
        resultItem: {
          highlight: true,
        },
        events: {
          input: {
            selection: (event) => {
              const selection = event.detail.selection.value;
              selection.remover = false;
              adiciciona_produto_e_verifica_adicao(selection);
            },
          },
        },
      });
      inicia();
      function inicia() {
        json_data = document.getElementById('json_data').textContent;
        if (json_data == "") {
          console.log(json_data);
          ob = [];
          objProdutos.value = ob;
        } else {
          json_data = JSON.parse(json_data);
          json_data = JSON.parse(json_data);
          objProdutos.value = JSON.stringify(json_data);
          ob = json_data;
        }
        atualiza_obj();
      }
      function adiciciona_produto_e_verifica_adicao(item) {
        item_adicionado = false;
        for (let i = 0; i < ob.length; i++) {
          if (item.id == ob[i].id) {
            item_adicionado = true
          }
        }
        if (!item_adicionado) {
          ob.push(item);
          resultado.innerHTML += `
          <li id="li-${item.id}" class="list-group-item d-flex p-2 bd-highlight justify-content-between">${item.produto}
            <div class="form-row form-inline">
              Quantidade: 
              <input name='quantidade-${item.id}' id='quantidade-${item.id}' type="number" class="form-text form-control mr-2 ml-2" 
              onchange="modifica_quantidade(${item.id})" required>
            <a href="#" class="btn btn-danger li-produto mr-1" onclick=removerProduto('li-${item.id}',${item.id})>
              <i class="fas fa-trash-can"></i>
            </a>
          </div>
        </li>`;
          atualiza_obj();
        }
        }
      
      function atualiza_obj() {
        objProdutos.value = JSON.stringify(ob);
        for (let i = 0; i < ob.length; i++) {
          if(ob[i].qtd) {
            id_qtd = "qtd-"+ob[i].id;
            element = document.getElementById(id_qtd);
            element.value = ob[i].qtd;
          }
        }
      }
      function removerProduto(item, id) {
        for (let i = 0; i < ob.length; i++) {
          if (ob[i].id == id) {
            ob[i].delete = true;
            ob[i].remover = true;
            // ob.splice(i, 1);
            document.getElementById(item).remove();
          }
        }
        atualiza_obj();
      }

      function modifica_quantidade(item) {
        for (let i = 0; i < ob.length; i++) {
          if (ob[i].id == item) {
            id_qtd = "quantidade-"+item;
            let obj = document.getElementById(id_qtd);
            ob[i].qtd = obj.value;
            atualiza_obj();
            console.log(ob);
          }
        }
       atualiza_obj();
      }
    </script>
{% endblock conteudo %}

produto/templates/produto/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block titulo %}| Listagem de Produtos{% endblock titulo %}
{% block conteudo %}
<div class="wrapper">
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2 d-flex-inline justify-content-between">
            <div class="col">
              <h1>Produtos</h1>
            </div>
            <div class="col d-flex justify-content-end">
              <a href="{% url 'produto:add' %}" class="btn btn-info"><i class="fa fa-add"></i> Criar Produto</a>
            </div>
          
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-12">
           <div class="card">
              <div class="card-header">
                <h3 class="card-title">Listagem dos produtos</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                <table id="tabela" class="table table-bordered table-striped">
                  <thead>
                  <tr>
                    <th>ID</th>
                    <th>Produto</th>
                    <th>Descrição</th>
                    <th>Tipo</th>
                    {% comment %} <th>Total de Itens</th> {% endcomment %}
                    <th>Imagem</th>
                    <th>Ações</th>
                  </tr>
                  </thead>
                  <tbody>
                    {% for produto in produtos %}
                  <tr>
                    <td>{{produto.id}}</td>
                    <td>{{produto.nome}}</td>
                    <td>{{produto.descricao_curta}}</td>
                    <td>{{produto.get_tipo_display}}</td>
                    <td>{% if produto.imagem %}<img src="{{produto.imagem.url}}" class="img-fluid" style="width:50px;" />{% else %}Produto sem Imagem{% endif %}</td>
                    <td>
                      <ul class="navbar-nav navbar-no-expand ml-2">
                        <li class="nav-item ml-2"><a href="{% url 'produto:edit' produto.id %}" class="btn btn-primary"><i class="fas fa-pen-to-square"></i></a></li>
                        <li class="nav-item ml-2"><a href="{% url 'produto:del' produto.id %}" class="btn btn-danger"><i class="fas fa-trash-can"></i></a></li>
                      </ul>
                    
                    </td>
                  </tr>
                  {% endfor %}
                  </tbody>
                  <tfoot>
                  <tr>
                    <th>ID</th>
                    <th>Produto</th>
                    <th>Descrição</th>
                    <th>Tipo</th>
                    <th>Imagem</th>
                    <th>Ações</th>
                  </tr>
                  </tfoot>
                </table>
                <div class="row">
                  <div class="col d-flex align-content-center">
                    {% include 'partials/_pagination.html' %}
                  </div>
                </div>
              </div>
              <!-- /.card-body -->
            </div>
            <!-- /.card -->
          </div>
          <!-- /.col -->
        </div>
        <!-- /.row -->
      </div>
      <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->
</div>
</div>
{% endblock conteudo %}